# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TextToPolygon
                                 A QGIS plugin
 This plugin converts text into vector geometries (polygons)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-23
        copyright            : (C) 2025 by Matthieu Viry
        email                : matthieu.viry@cnrs.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Matthieu Viry'
__date__ = '2025-04-23'
__copyright__ = '(C) 2025 by Matthieu Viry'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TextToPolygon class from file TextToPolygon.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .text_to_polygon import TextToPolygonPlugin
    return TextToPolygonPlugin()
